# Generated by Django 5.1.3 on 2024-11-06 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop_leads',
            name='location',
            field=models.CharField(choices=[('Mumbai', 'Mumbai'), ('Bengaluru', 'Bengaluru')], max_length=100),
        ),
        migrations.AlterField(
            model_name='workshop_leads',
            name='orderId',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
