# Generated by Django 5.1.3 on 2024-11-08 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_type', models.CharField(choices=[('enquiry', 'Enquiry Lead'), ('workshop', 'Workshop Lead')], max_length=10)),
                ('lead_id', models.PositiveIntegerField()),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('assigned_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_leads', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('lead_type', 'lead_id')},
            },
        ),
    ]
