# Generated by Django 5.1.3 on 2024-11-19 03:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remarks',
            name='enquiry_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='app.enquiry_leads'),
        ),
    ]
