# Generated by Django 5.1.3 on 2024-11-18 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Remarks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Follow Up', 'Follow Up'), ('Converted', 'Converted'), ('Closed', 'Closed')], default='Pending', max_length=100)),
                ('remark_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enquiry_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='remarks', to='app.enquiry_leads')),
                ('workshop_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Workshop_Leads_remarks', to='app.workshop_leads')),
            ],
        ),
    ]
