# Generated by Django 5.1.2 on 2024-10-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_service_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Connected', 'Connected'), ('Qualified', 'Qualified'), ('Lost', 'Lost')], default='New', max_length=100),
        ),
    ]
