# Generated by Django 5.1.3 on 2024-11-19 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_remarks_enquiry_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='remarks',
            name='workshop_lead',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Workshop_Leads_remarks', to='app.workshop_leads'),
        ),
    ]
