# Generated by Django 5.1.1 on 2025-02-13 11:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemarksHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
                ('remark_text', models.TextField()),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('remarks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.remarks')),
            ],
        ),
    ]
