# Generated by Django 5.1.3 on 2024-11-07 05:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_student_states_installment'),
    ]

    operations = [
        migrations.CreateModel(
            name='EnquiryTelecaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Follow Up', 'Follow Up'), ('Converted', 'Converted'), ('Closed', 'Closed')], default='Pending', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Bengaluru', 'Bengaluru')], max_length=100)),
                ('assigned_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_telecaller', to='app.enquiry_leads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enquiry_calls', to='app.users')),
            ],
        ),
        migrations.CreateModel(
            name='WorkshopTelecaller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('follow_up_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Contacted', 'Contacted'), ('Follow Up', 'Follow Up'), ('Payment Confirmed', 'Payment Confirmed'), ('Closed', 'Closed')], default='Pending', max_length=100)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('location', models.CharField(choices=[('Mumbai', 'Mumbai'), ('Bengaluru', 'Bengaluru')], max_length=100)),
                ('assigned_workshop_lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_telecaller', to='app.workshop_leads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workshop_calls', to='app.users')),
            ],
        ),
    ]
