# Generated by Django 5.1.3 on 2024-11-20 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_leadsource_enquiry_leads_lead_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadsource',
            name='name',
            field=models.CharField(default='website', max_length=255, unique=True),
        ),
    ]
