# Generated by Django 5.1.3 on 2024-11-20 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_leadsource_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enquiry_leads',
            name='lead_source',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='app.leadsource'),
        ),
    ]
