# Generated by Django 5.1.2 on 2024-10-29 04:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_lead_created_at_alter_lead_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='app.lead'),
        ),
        migrations.AlterField(
            model_name='communication',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='app.student'),
        ),
        migrations.CreateModel(
            name='CommunicationHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('communication_type', models.CharField(choices=[('email', 'Email'), ('call', 'Call'), ('sms', 'SMS')], max_length=10)),
                ('content', models.TextField()),
                ('communication_date', models.DateTimeField()),
                ('status', models.CharField(max_length=20)),
                ('communication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='app.communication')),
            ],
        ),
    ]
