# Generated by Django 5.1.2 on 2024-11-05 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_communication_id_alter_communication_lead_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='communication',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
